version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=your_password_here
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - web

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.2
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "5001:5001"
    depends_on:
      - elasticsearch
    networks:
      - web

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=your_password_here
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - web

volumes:
  es_data:
    driver: local

networks:
  web:
    external: true

# docker-compose up -d elasticsearch
# docker-compose exec elasticsearch bash

# curl -X POST "http://localhost:9200/_security/user/kibana_system/_password " -u elastic:your_password_here -H "Content-Type: application/json" -d '{"password": "your_password_here" }'
       